export default [
	{
		id: 1,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/SpaWellness/gsmSaloon.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.6',
		name: 'GSM Saloons',
		membership: 'Annual Membership start from 11999/-',
	},
	{
		id: 2,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/SpaWellness/roversSaloon.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.2',
		name: 'Soccer Saloon',
		membership: 'Annual Membership start from 11999/-',
	},
	{
		id: 3,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/SpaWellness/soccerSaloon.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.7',
		name: 'Rovers Saloon',
		membership: 'Annual Membership start from 11999/-',
	},
	{
		id: 4,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/SpaWellness/westDelhiSaloon.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.8',
		name: 'West Delhi Saloon',
		membership: 'Annual Membership start from 11999/-',
	},
]
