/* eslint import/no-anonymous-default-export: [2, {"allowArray": true}] */
export default [
	{
		id: 1,
		info: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/infoicon.png',
		share: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/shareicon.png',
		file: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/pdffile.png',
		filename: 'invoice.pdf',
		filesize: 'Filesize',
		filemb: '5.7MB',
		download: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/downloadicon.png',
		dateandtime: ' 01/07/2021 6:12:12 am',
	},
	{
		id: 2,
		info: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/infoicon.png',
		share: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/shareicon.png',
		file: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/image.png',
		filename: 'image.png',
		filesize: 'Filesize',
		filemb: '10.7MB',
		download: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/downloadicon.png',
		dateandtime: ' 01/07/2021 6:12:12 am',
	},
	{
		id: 3,
		info: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/infoicon.png',
		share: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/shareicon.png',
		file: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/pdffile.png',
		filename: 'image.png',
		filesize: 'Filesize',
		filemb: '50.7MB',
		download: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/downloadicon.png',
		dateandtime: ' 01/07/2021 6:12:12 am',
	},
	{
		id: 4,
		info: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/infoicon.png',
		share: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/shareicon.png',
		file: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/image.png',
		filename: 'invoice.pdf',
		filesize: 'Filesize',
		filemb: '500.7MB',
		download: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/downloadicon.png',
		dateandtime: ' 01/07/2021 6:12:12 am',
	},
	{
		id: 5,
		info: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/infoicon.png',
		share: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/shareicon.png',
		file: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/pdffile.png',
		filename: 'image.svg',
		filesize: 'Filesize',
		filemb: '55.7MB',
		download: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/downloadicon.png',
		dateandtime: ' 01/07/2021 6:12:12 am',
	},
	{
		id: 6,
		info: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/infoicon.png',
		share: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/shareicon.png',
		file: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/pdffile.png',
		filename: 'invoice.pdf',
		filesize: 'Filesize',
		filemb: '56.7MB',
		download: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/downloadicon.png',
		dateandtime: ' 01/07/2021 6:12:12 am',
	},
	{
		id: 7,
		info: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/infoicon.png',
		share: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/shareicon.png',
		file: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/image.png',
		filename: 'image.png',
		filesize: 'Filesize',
		filemb: '56.7MB',
		download: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/downloadicon.png',
		dateandtime: ' 01/07/2021 6:12:12 am',
	},
	{
		id: 8,
		info: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/infoicon.png',
		share: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/shareicon.png',
		file: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/image.png',
		filename: 'invoice.pdf',
		filesize: 'Filesize',
		filemb: '5.9MB',
		download: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/downloadicon.png',
		dateandtime: ' 01/07/2021 6:12:12 am',
	},
]
