export default [
	{
		id: 1,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/apollo.jpg',
		city: 'Chennai',
		area: 'Greams Road',
		ratings: '4.6',
		name: 'Apollo Hospital',
	},
	{
		id: 2,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/sims.jpg',
		city: 'Chennai',
		area: 'Vadapalani',
		ratings: '4.2',
		name: 'SIMS Hospital',
	},
	{
		id: 3,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/fortis.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.7',
		name: 'Fortis Malar Hospital',
	},
	{
		id: 4,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/srm.jpg',
		city: 'Chennai',
		area: 'Adyar',
		ratings: '4.8',
		name: 'SRM Hospital',
	},
	{
		id: 5,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/frontier.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.2',
		name: 'Frontier Lifeline Hospital',
	},
	{
		id: 6,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/hospp.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.7',
		name: 'Global Hospitals & Health City',
	},
	{
		id: 7,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/srm.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.8',
		name: 'Mehta Hospitals Pvt.Ltd',
	},
	{
		id: 8,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/hospp.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.8',
		name: 'Sri Ramachandra Medical Centre',
	},
]
