/* eslint import/no-anonymous-default-export: [2, {"allowArray": true}] */
export default [
	{
		id: 1,
		product: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/productstore.png',
		size: '60 Capsules | 500 mg ',
		lab: 'Lab Naturals-Immunity Booster',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		ratewrite: 'MRP $399',
		rate: '$399',
	},
	{
		id: 2,
		product: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/productstore.png',
		size: '60 Capsules | 500 mg ',
		lab: 'Lab Naturals-Immunity Booster',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		ratewrite: 'MRP $399',
		rate: '$399',
	},
	{
		id: 3,
		product: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/productstore.png',
		size: '60 Capsules | 500 mg ',
		lab: 'Lab Naturals-Immunity Booster',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		ratewrite: 'MRP $399',
		rate: '$399',
	},
	{
		id: 4,
		product: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/productstore.png',
		size: '60 Capsules | 500 mg ',
		lab: 'Lab Naturals-Immunity Booster',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		ratewrite: 'MRP $399',
		rate: '$399',
	},
	{
		id: 5,
		product: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/productstore.png',
		size: '60 Capsules | 500 mg ',
		lab: 'Lab Naturals-Immunity Booster',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		ratewrite: 'MRP $399',
		rate: '$399',
	},
	{
		id: 6,
		product: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/productstore.png',
		size: '60 Capsules | 500 mg ',
		lab: 'Lab Naturals-Immunity Booster',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		ratewrite: 'MRP $399',
		rate: '$399',
	},
	{
		id: 7,
		product: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/productstore.png',
		size: '60 Capsules | 500 mg ',
		lab: 'Lab Naturals-Immunity Booster',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		ratewrite: 'MRP $399',
		rate: '$399',
	},
]
