export default [
	{
		id: 1,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/nursingCareHome.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.6',
		name: 'KMCH Home Servive',
	},
	{
		id: 2,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/dressing.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.2',
		name: 'Royal Care Home Servive',
	},
	{
		id: 3,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/physio.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.7',
		name: 'Annai Home Servive',
	},
	{
		id: 4,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/postt.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.8',
		name: 'PSG Home Servive',
	},
	{
		id: 5,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/kalamayi-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.2',
		name: 'Apollo Home Servive',
	},
	{
		id: 6,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/chai-wellness-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.7',
		name: 'REX Home Servive',
	},
	{
		id: 7,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/vivek-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.8',
		name: 'Ganga Home Servive',
	},
]
