/* eslint import/no-anonymous-default-export: [2, {"allowArray": true}] */
export default [
	{
		id: 1,
		profilepic: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/tick-care.svg',
		view: 'View Profile',
		name: 'Dr.Thiru',
		image1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/stethoscope.svg',
		experience: 'Dentist,23 Years Experience Overall',
		image2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/location.svg',
		address: 'Mogappair East,Dr.Vijay`s Hospital, Chennai',
		image3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/phone.svg',
		phonenum: '9876543210',
		reviewone: '99%',
		reviewtwo: '(258 Reviews)',
		fees: '500',
		image4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/calendar.svg',
		status: 'Available Today',
	},
	{
		id: 2,
		profilepic: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/tick-care.svg',
		view: 'View Profile',
		name: 'Dr.Karthick',
		image1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/stethoscope.svg',
		experience: 'Dentist,23 Years Experience Overall',
		image2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/location.svg',
		address: 'Mogappair East,Dr.Vijay`s Hospital, Chennai',
		image3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/phone.svg',
		phonenum: '9876543210',
		reviewone: '99%',
		reviewtwo: '(258 Reviews)',
		fees: '700',
		image4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/calendar.svg',
		status: 'Not Available',
	},
	{
		id: 3,
		profilepic: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/tick-care.svg',
		view: 'View Profile',
		name: 'Dr.Dinesh',
		image1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/stethoscope.svg',
		experience: 'Dentist,23 Years Experience Overall',
		image2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/location.svg',
		address: 'Mogappair East,Dr.Vijay`s Hospital, Chennai',
		image3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/phone.svg',
		phonenum: '9876543210',
		reviewone: '99%',
		reviewtwo: '(258 Reviews)',
		fees: '400',
		image4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/calendar.svg',
		status: 'Available Today',
	},
	{
		id: 4,
		profilepic: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/tick-care.svg',
		view: 'View Profile',
		name: 'Dr.Ranjith',
		image1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/stethoscope.svg',
		experience: 'Dentist,23 Years Experience Overall',
		image2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/location.svg',
		address: 'Mogappair East,Dr.Vijay`s Hospital, Chennai',
		image3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/phone.svg',
		phonenum: '9876543210',
		reviewone: '99%',
		reviewtwo: '(258 Reviews)',
		fees: '400',
		image4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/calendar.svg',
		status: 'Available Today',
	},
]
