// eslint-disable-next-line import/no-anonymous-default-export
export default [
	{
		id: 1,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/pradi-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.6',
		name: 'Pradi Yoga Center',
		membership: 'Annual Membership start from 11999/-',
	},
	{
		id: 2,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/kalamayi-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.2',
		name: 'Kalamayi Yoga',
		membership: 'Annual Membership start from 11999/-',
	},
	{
		id: 3,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/chai-wellness-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.7',
		name: 'Chai Wellness Yoga',
		membership: 'Annual Membership start from 11999/-',
	},
	{
		id: 4,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/vivek-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.8',
		name: 'Vivek Yoga',
		membership: 'Annual Membership start from 11999/-',
	},
	{
		id: 5,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/kalamayi-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.2',
		name: 'Kalamayi Yoga',
		membership: 'Annual Membership start from 11999/-',
	},
	{
		id: 6,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/chai-wellness-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.7',
		name: 'Chai Wellness Yoga',
		membership: 'Annual Membership start from 11999/-',
	},
	{
		id: 7,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/vivek-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.8',
		name: 'Vivek Yoga',
		membership: 'Annual Membership start from 11999/-',
	},
]
