export const fitnessMenuList = [
	{
		name: 'Trainers',
		path: 'fitnessTrainers',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitnessIcons/fitnessCenter.svg',
		index: 0,
		color: '#0095EB',
	},
	{
		name: 'Fitness Centers',
		path: 'fitnessCenters',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitnessIcons/trainers.svg',
		index: 1,
		color: '#0095EB',
	},
	{
		name: 'Home Services',
		path: 'fitnessHomeServices',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitnessIcons/homeService.svg',
		index: 2,
		color: '#0095EB',
	},
	{
		name: 'Online Training',
		path: 'fitnessOnlineTraining',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitnessIcons/onlineTraining.svg',
		index: 3,
		color: '#0095EB',
	},
	{
		name: 'Packages',
		path: 'fitnessPackages',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitnessIcons/packages.svg',
		index: 4,
		color: '#0095EB',
	},
	{
		name: 'Consult',
		path: 'fitnessConsult',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitnessIcons/consult.svg',
		index: 5,
		color: '#0095EB',
	},
	{
		name: 'Article',
		path: 'fitnessArticle',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitnessIcons/article.svg',
		index: 7,
		color: '#0095EB',
	},
	{
		name: 'FAQ',
		path: 'fitnessFAQ',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitnessIcons/faq.svg',
		index: 6,
		color: '#0095EB',
	},
	{
		name: 'Store',
		path: 'fitnessStore',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitnessIcons/store.svg',
		index: 8,
		color: '#0095EB',
	},
]
