export const mainMenuList = [
	{
		name: 'Care',
		path: 'care',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/care.svg',
		index: 0,
		color: '#7047EA',
		home: '/care',
	},
	{
		name: 'Fitness',
		path: 'fitness',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/fitness.svg',
		index: 1,
		color: ' #0095EB ',
		home: '/fitness',
	},
	{
		name: 'Mind',
		path: 'mind',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/yoga.svg',
		index: 2,
		color: '#0CC593',
		home: '/mind',
	},
	{
		name: 'Spa & Wellness',
		path: 'spawellness',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/spa.svg',
		index: 3,
		color: '#0693EA',
		home: '/',
	},
	{
		name: 'Sports',
		path: 'sports',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/sport.svg',
		index: 4,
		color: '#FF2083',
		home: '/',
	},
	{
		name: 'Shopping Cart',
		path: 'shopping',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/stpre.svg',
		index: 5,
		color: '#7047EA',
		home: '/',
	},
	{
		name: 'Live',
		path: 'live',
		img: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/Icon material-live-tv.svg',
		index: 6,
		color: '#7047EA',
		home: '/',
	},
]
