import {makeStyles} from '@material-ui/core/styles'

export const useStyles = makeStyles(theme => ({
	chatArea_CardContent: {
		paddingBottom: '10px !important',
		background: 'transparent linear-gradient(139deg, #FFFFFFCC 0%, #FFFFFFB3 100%) 0% 0% no-repeat padding-box',
		backgroundColor: '#00000026',
		opacity: 1,
		boxShadow: '0px 3px 6px #00000026',
		backdropFilter: 'blur(25px)',
	},
	prevSty: {
		height: 387,
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'center',
		textAlign: 'center',
	},
	wrap: {
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'center',
		gap: 46,
	},
	logoName: {
		color: 'red',
		fontWeight: 600,
		fontSize: 24,
	},
	quest: {
		paddingBottom: 24,
		fontSize: 16,
	},
	topHeader: {
		background: 'transparent linear-gradient(274deg, #FAFAFA40 0%, #FFFFFFCC 100%) 0% 0% no-repeat padding-box',
		border: '1px solid #FFFFFF80',
		backdropFilter: 'blur(25px)',
		position: 'static',
		display: 'flex',
		justifyContent: 'space-between',
		boxShadow: '0px 3px 6px #00000026',
		height: '70px',
		padding: '10px',
		zIndex: 1,
		alignItems: 'center',
		'&:hover': {
			cursor: 'pointer',
		},
	},
	flexOrder: {
		display: 'flex',
		gap: 14,
		alignItems: 'center',
	},
	headerLogo: {
		display: 'flex',
		alignItems: 'center',
		[theme.breakpoints.down('sm')]: {
			width: '30px',
			height: '30px',
			paddingRight: '6px',
		},
	},
	menuIcon: {
		background: theme.palette.care.main,
		borderRadius: 10,
		color: '#fff',
		width: '46px',
		height: '42px',
		'&:hover': {
			background: theme.palette.care.main,
		},
	},
	chatArea_name: {
		color: '#4B5155',
		fontSize: '16px',
		fontFamily: 'poppins',
		fontWeight: 500,
		lineHeight: '21px',
		alignSelf: 'center',
		opacity: 1,
	},
	catList: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'flex-start',
	},
	msg_area: {
		padding: '10px',
		height: '45vh',
		overflow: 'auto',
		minHeight: '45vh',
	},
	resetBtn: {
		border: '1px solid #7047EA',
		borderRadius: '10px',
		color: '#7047EA',
		opacity: 1,
		textTransform: 'capitalize',

		height: '36px',
		alignSelf: 'center',
		'&:hover, &:focus, &:active': {
			backgroundColor: 'transparent',
			color: '#7047EA',
		},
	},
	systemImg: {
		width: '90px',
		height: '40px',
		margin: '0px 10px 15px 0px',
		alignSelf: 'flex-end',
		[theme.breakpoints.down('sm')]: {
			width: '30px',
			height: '30px',
			paddingRight: '6px',
		},
	},
	msgWrap: {
		display: 'flex',
	},
	rightMsg_wrap: {
		flexDirection: 'row-reverse',
		display: 'flex',
		justifyContent: 'end',
	},
	leftMessageContent: {
		// background: '#FFFFFF',
		background: '#7047ea30',
		maxWidth: '400px',
		width: 'auto',
		padding: '12px',
		fontSize: '12px',
		borderRadius: '10px 10px 10px 0px',
		color: '#2A2A2A',
		opacity: 0.8,
		[theme.breakpoints.down('sm')]: {
			maxWidth: '200px',
		},
	},
	rightMessageContent: {
		background: '#779BEB4C 0% 0% no-repeat padding-box',
		// background: '#887CE3',
		color: '#364461',
		maxWidth: '400px',
		width: 'auto',
		padding: '12px',
		fontSize: '12px',
		borderRadius: '10px 0px 10px 10px',
		opacity: 1,
	},
	timeDisplayFont: {
		fontSize: '10px',
		marginTop: '5px',
		font: 'normal 10px/16px Sofia Pro',
		color: '#AFBBC6',
		opacity: 1,
	},
	sysMsg: {
		backgroundColor: '#F4F5F8',
		padding: '5px 10px',
		font: '12px/18px Poppins',
		color: '#2A2A2A',
		opacity: '0.59',
	},

	footer: {
		padding: '0px 10px',
	},
	searchBox: {
		width: '100%',
		marginBottom: '0px',
		borderRadius: '10px',
		background: '#FFFF',
		border: '1px solid #DBE5ED',
		'& .MuiOutlinedInput-root': {
			height: '48px',
		},
		'& .MuiTextField-root': {
			marginTop: '14px',
		},
		'& .MuiOutlinedInput-adornedEnd': {
			paddingRight: '5px',
		},
		'& .MuiOutlinedInput-notchedOutline': {
			border: '0px',
		},
	},
	sendIconLayer: {
		background: '#7047EA',
		borderRadius: '50px',
		display: 'flex',
		alignItems: 'center',
		width: '35px',
		height: '35px',
		justifyContent: 'center',
		borderRadius: '10px',
		opacity: 1,
	},
	navigationOutlinedIcon: {
		transform: 'rotate(-45deg)',
		fontSize: '20px',
		color: '#FFFFFF',
		cursor: 'pointer',
		margin: '0px 0px 5px 5px',
	},
	specialityBtn: {
		border: '1px solid #7047EA',
		color: '#7047EA',
		margin: '3px',
		fontSize: '12px',
		padding: '1px 5px',
		fontSize: '12px',
	},
	chatOpt_Btn: {
		border: '1px solid #7047EA',
		color: '#7047EA',
		margin: '3px',
		fontSize: '12px',
		fontSize: '12px',
		textTransform: 'none',
		borderRadius: 6,
		paddingBlock: 8,
		paddingInline: 14,
	},
	emojiLayer: {
		margin: '0px 10px 15px 0px',
		alignSelf: 'center',
		paddingBottom: '9px',
	},
	rightItems: {
		background: '#779BEB4C',
		marginLeft: 'auto',
		width: 'fit-content',
		borderRadius: '10px 10px 0px 10px',
		marginRight: '10px',
	},
	amountText: {
		fontWeight: 'bold',
		fontSize: '17px',
		color: '#000000',
		paddingLeft: '10px',
	},
	payBtn: {
		background: 'transparent linear-gradient(254deg,#7047EA, #9847EA) 0% 0% no-repeat padding-box',
		padding: '0px 15px',
		borderRadius: '17px',
		color: 'white',
		fontSize: '13px',
		height: '30px',
		alignSelf: 'center',
		textTransform: 'capitalize',
	},
	paymentError: {
		color: '#CF0707',
		margin: '6px 0px',
		background: '#6E030324',
		padding: '3px 11px',
		fontSize: '12px',
		fontWeight: 600,
		textTransform: 'capitalize',
		borderRadius: '3px',
	},
	successItem: {
		background: '#036E1924',
		color: '#036E19',
		fontSize: '13px',
	},
	padding0: {
		padding: '0px !important',
	},
	payDisable: {
		opacity: '0.5',
		color: 'white !important',
	},
	tryDisable: {
		opacity: '0.5',
		color: 'grey !important',
	},
	chatOptDisabl: {
		opacity: 0.5,
		border: '1px solid rgb(184 185 197) !important',
		color: '#494564 !important',
	},
	tryAgainBtn: {
		backgroundColor: '#faf5f5',
		height: '25px',
		fontSize: '14px',
		fontWeight: 500,
		marginTop: '8px',
		'& .MuiButton-label': {
			fontSize: '12px',
			color: 'red',
		},
	},
}))
