/* eslint import/no-anonymous-default-export: [2, {"allowArray": true}] */
export default [
	{
		id: 1,
		head: 'Comprehensive full body check-up',
		safeimg: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/safe-care.svg',
		subhead: 'Includes 91 Tests',
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/1mg.svg',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		list: 'Amylase ',
		listcontent: 'Complete blood count Kidney Function test +more',
		price: 'Rs.399',
		overwrite: 'Rs.599',
	},
	{
		id: 2,
		head: 'Comprehensive full body check-up',
		safeimg: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/safe-care.svg',
		subhead: 'Includes 91 Tests',
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/1mg.svg',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		list: 'Amylase ',
		listcontent: 'Complete blood count Kidney Function test +more',
		price: 'Rs.399',
		overwrite: 'Rs.599',
	},
	{
		id: 3,
		head: 'Comprehensive full body check-up',
		safeimg: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/safe-care.svg',
		subhead: 'Includes 91 Tests',
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/1mg.svg',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		list: 'Amylase ',
		listcontent: 'Complete blood count Kidney Function test +more',
		price: 'Rs.399',
		overwrite: 'Rs.599',
	},
	{
		id: 4,
		head: 'Comprehensive full body check-up',
		safeimg: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/safe-care.svg',
		subhead: 'Includes 91 Tests',
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/1mg.svg',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		list: 'Amylase ',
		listcontent: 'Complete blood count Kidney Function test +more',
		price: 'Rs.399',
		overwrite: 'Rs.599',
	},
	{
		id: 5,
		head: 'Comprehensive full body check-up',
		safeimg: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/safe-care.svg',
		subhead: 'Includes 91 Tests',
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/1mg.svg',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		list: 'Amylase ',
		listcontent: 'Complete blood count Kidney Function test +more',
		price: 'Rs.399',
		overwrite: 'Rs.599',
	},
	{
		id: 6,
		head: 'Comprehensive full body check-up',
		safeimg: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/safe-care.svg',
		subhead: 'Includes 91 Tests',
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/1mg.svg',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		list: 'Amylase ',
		listcontent: 'Complete blood count Kidney Function test +more',
		price: 'Rs.399',
		overwrite: 'Rs.599',
	},
	{
		id: 7,
		head: 'Comprehensive full body check-up',
		safeimg: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/safe-care.svg',
		subhead: 'Includes 91 Tests',
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/icons/1mg.svg',
		rating: '3.4',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		list: 'Amylase ',
		listcontent: 'Complete blood count Kidney Function test +more',
		price: 'Rs.399',
		overwrite: 'Rs.599',
	},
]
