/* eslint import/no-anonymous-default-export: [2, {"allowArray": true}] */
export default [
	{
		id: 1,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/QuizesImage.png',
		name: 'Dr John Doe',
		job: 'Senior Virologist ',
		heading: ' Is corona virus a communicable disease?',
		text: ' Trem aperiam, eaque ipsa quae avitae dicta sunt explicabo sequi nesciuntTrem aperiam, eaque ipsa quae ab illo inventore veritatis et....',
		color: '#FEC56C',
		colorjob: '#c39f68',
		bgcolor: ' transparent linear-gradient(102deg, #FFF0D9 0%, #FFFFFF40 100%) 0% 0% no-repeat padding-box',
		shadow: '0px 10px 32px #E0474E29',
	},
	{
		id: 2,
		name: 'Dr John Doe',
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/QuizesImage.png',
		job: 'Senior Virologist ',
		heading: ' Is corona virus a communicable disease?',
		text: ' Trem aperiam, eaque ipsa quae avitae dicta sunt explicabo sequi nesciuntTrem aperiam, eaque ipsa quae ab illo inventore veritatis et....',
		color: '#E0474E',
		colorjob: '#9B4A59',
		bgcolor: 'transparent linear-gradient(102deg, #E0474E32 0%, #FFFFFF40 100%) 0% 0% no-repeat padding-box',
		shadow: '0px 10px 32px #E0474E29',
	},
	{
		id: 3,
		name: 'Dr John Doe',
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/QuizesImage.png',
		job: 'Senior Virologist ',
		heading: ' Is corona virus a communicable disease?',
		text: ' Trem aperiam, ,eaque ipsa quae avitae dicta sunt explicabo sequi nesciuntTrem aperiam, eaque ipsa quae ab illo inventore veritatis et....',
		color: '#00B592',
		colorjob: '#1a7563',
		bgcolor: 'transparent linear-gradient(102deg, #00B59232 0%, #FFFFFF40 100%) 0% 0% no-repeat padding-box',
		shadow: '0px 10px 32px #E0474E29',
	},
]
