export default [
	{
		id: 1,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/scann.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.6',
		name: 'Shanthi Labs & Scans',
	},
	{
		id: 2,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/scannn.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.2',
		name: 'Covai Scan Center',
	},
	{
		id: 3,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/labbb.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.7',
		name: 'Annai Scan & Diagnostics',
	},
	{
		id: 4,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/labss.jpg',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.8',
		name: 'PSG Labs',
	},
	{
		id: 5,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/kalamayi-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.2',
		name: 'Apollo Home Servive',
	},
	{
		id: 6,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/chai-wellness-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.7',
		name: 'REX Home Servive',
	},
	{
		id: 7,
		src: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Mind/vivek-yoga.png',
		city: 'Chennai',
		area: 'T-Nagar',
		ratings: '4.8',
		name: 'Ganga Home Servive',
	},
]
