/* eslint import/no-anonymous-default-export: [2, {"allowArray": true}] */
export default [
	{
		id: 1,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/userexperience.png',
		name: 'Dr. John doe',
		prefessional: '26 old-Professional',
		story: 'Excellent Experience consulting on LFYnGO. I could save my life with out going to clinic and the....',
		Location: 'Chennai',
	},
	{
		id: 2,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/userexperience.png',
		name: 'Dr. John doe',
		prefessional: '26 old-Professional',
		story: 'Excellent Experience consulting on LFYnGO. I could save my life with out going to clinic and the....',
		Location: 'Chennai',
	},
	{
		id: 3,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/userexperience.png',
		name: 'Dr. John doe',
		prefessional: '26 old-Professional',
		story: 'Excellent Experience consulting on LFYnGO. I could save my life with out going to clinic and the....',
		Location: 'Chennai',
	},
	{
		id: 4,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/userexperience.png',
		name: 'Dr. John doe',
		prefessional: '26 old-Professional',
		story: 'Excellent Experience consulting on LFYnGO. I could save my life with out going to clinic and the....',
		Location: 'Chennai',
	},
	{
		id: 5,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/userexperience.png',
		name: 'Dr. John doe',
		prefessional: '26 old-Professional',
		story: 'Excellent Experience consulting on LFYnGO. I could save my life with out going to clinic and the....',
		Location: 'Chennai',
	},
	{
		id: 6,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/userexperience.png',
		name: 'Dr. John doe',
		prefessional: '26 old-Professional',
		story: 'Excellent Experience consulting on LFYnGO. I could save my life with out going to clinic and the....',
		Location: 'Chennai',
	},
	{
		id: 7,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/userexperience.png',
		name: 'Dr. John doe',
		prefessional: '26 old-Professional',
		story: 'Excellent Experience consulting on LFYnGO. I could save my life with out going to clinic and the....',
		Location: 'Chennai',
	},
	{
		id: 8,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/picture/userexperience.png',
		name: 'Dr. John doe',
		prefessional: '26 old-Professional',
		story: 'Excellent Experience consulting on LFYnGO. I could save my life with out going to clinic and the....',
		Location: 'Chennai',
	},
]
