/* eslint import/no-anonymous-default-export: [2, {"allowArray": true}] */

export default [
	{
		id: 1,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/hospital1.png',
		hospitalName: 'Apollo Hospital',
		rating: '4.8',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		branch: 'Chennai- T-Nagar',
		doctor1: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor2: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor3: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor4: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor5: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor6: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor7: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor8: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor9: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor10: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor11: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor12: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
	},
	{
		id: 2,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/hospital2.png',
		hospitalName: 'Apollo Hospital',
		rating: '4.8',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		branch: 'Chennai- T-Nagar',
		doctor1: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor2: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor3: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor4: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor5: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor6: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor7: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor8: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor9: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor10: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor11: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor12: 'https://ik.imagekit.io/lyfngo/web_b2c/publichttps://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
	},
	{
		id: 3,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/imageshttps://ik.imagekit.io/lyfngo/web_b2c/public/Hospital-care/hospital3.png',
		hospitalName: 'Apollo Hospital',
		rating: '4.8',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		branch: 'Chennai- T-Nagar',
		doctor1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor5: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor6: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor7: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor8: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor9: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor10: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor11: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor12: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
	},
	{
		id: 4,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/hospital4.png',
		hospitalName: 'Apollo Hospital',
		rating: '4.8',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		branch: 'Chennai- T-Nagar',
		doctor1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor5: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor6: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor7: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor8: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor9: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor10: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor11: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor12: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
	},
	{
		id: 5,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/hospital1.png',
		hospitalName: 'Apollo Hospital',
		rating: '4.8',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		branch: 'Chennai- T-Nagar',
		doctor1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor5: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor6: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor7: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor8: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor9: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor10: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor11: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor12: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
	},
	{
		id: 6,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/hospital2.png',
		hospitalName: 'Apollo Hospital',
		rating: '4.8',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		branch: 'Chennai- T-Nagar',
		doctor1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor5: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor6: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor7: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor8: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor9: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor10: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor11: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor12: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
	},
	{
		id: 7,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/hospital3.png',
		hospitalName: 'Apollo Hospital',
		rating: '4.8',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		branch: 'Chennai- T-Nagar',
		doctor1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor5: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor6: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor7: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor8: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor9: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor10: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor11: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor12: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
	},
	{
		id: 8,
		image: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/hospital4.png',
		hospitalName: 'Apollo Hospital',
		rating: '4.8',
		star: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/glassycard/star.svg',
		branch: 'Chennai- T-Nagar',
		doctor1: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor2: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor3: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor4: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor5: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor6: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor7: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor8: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor9: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor10: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor11: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
		doctor12: 'https://ik.imagekit.io/lyfngo/web_b2c/public/images/Hospital-care/doctor.png',
	},
]
